/* =============================================================
   CZECH LEARNING DATA
   -------------------------------------------------------------
   HOW TO ADD A NEW WEEK:
   1. Copy one of the lesson objects below.
   2. Change the "id", "title" and "emoji".
   3. Fill in "vocab" (cz/en/note), "phrases" (cz/en) and
      "grammar" (title/note). Note is optional everywhere.
   4. Save. The whole website updates automatically.

   Tip: keep "cz" as the Czech word, "en" as the English meaning.
   Gender/word-type hints go in "note".
   ============================================================= */

const LESSONS = [
  /* ---------------------------------------------------------- */
  {
    id: "lesson1",
    title: "Lesson 1 — Czechia & Adjectives",
    emoji: "🏙️",
    vocab: [
      { cz: "Česko", en: "Czech Republic", note: "informal name" },
      { cz: "přátelský", en: "friendly", note: "adjective" },
      { cz: "cizinec", en: "foreigner", note: "plural: cizinci" },
      { cz: "mezinárodní", en: "international", note: "adjective" },
      { cz: "studie", en: "study", note: "feminine noun" },
      { cz: "ukázat", en: "to show", note: "ukázala = showed" },
      { cz: "patřit mezi", en: "to belong among / to be one of", note: "very common" },
      { cz: "země", en: "country", note: "feminine" },
      { cz: "žebříček", en: "ranking", note: "masculine" },
      { cz: "obsadit", en: "to occupy / rank", note: "obsadilo 8. místo" },
      { cz: "místo", en: "place, position", note: "neuter" },
      { cz: "svět", en: "world", note: "masculine" },
      { cz: "dokonce", en: "even", note: "adverb" },
      { cz: "nejlépe", en: "best", note: "superlative adverb" },
      { cz: "hodnotit", en: "to evaluate", note: "" },
      { cz: "bezpečnost", en: "safety", note: "feminine" },
      { cz: "možnost", en: "possibility", note: "feminine" },
      { cz: "najít", en: "to find", note: "perfective verb" },
      { cz: "práce", en: "work", note: "feminine" },
      { cz: "otevřenost", en: "openness", note: "feminine" },
      { cz: "zkušenost", en: "experience", note: "feminine" },
      { cz: "přestěhovat se", en: "to move (house/country)", note: "reflexive verb" },
      { cz: "žít", en: "to live", note: "žije = lives" },
      { cz: "více než", en: "more than", note: "useful expression" },
      { cz: "milion", en: "million", note: "masculine" },
      { cz: "obyvatel", en: "inhabitant", note: "masculine" },
      { cz: "oceňovat", en: "to appreciate", note: "" },
      { cz: "pracovní příležitost", en: "job opportunity", note: "" },
      { cz: "bezpečné prostředí", en: "safe environment", note: "" },
      { cz: "někteří", en: "some", note: "" },
      { cz: "navazování", en: "establishing / making", note: "from navazovat" },
      { cz: "přátelství", en: "friendship", note: "neuter" },
      { cz: "zpočátku", en: "at first", note: "" },
      { cz: "trochu", en: "a little", note: "" },
      { cz: "obtížný", en: "difficult", note: "obtížnější = more difficult" },
      { cz: "například", en: "for example", note: "" }
    ],
    phrases: [
      { cz: "Česko patří mezi nejpřátelštější země.", en: "The Czech Republic is among the friendliest countries." },
      { cz: "Obsadilo osmé místo.", en: "It ranked eighth." },
      { cz: "Dnes žije v České republice více než jeden milion cizinců.", en: "Today, more than one million foreigners live in the Czech Republic." },
      { cz: "Oceňují dobré pracovní příležitosti.", en: "They appreciate good job opportunities." },
      { cz: "Navazování přátelství může být obtížnější.", en: "Making friends can be more difficult." },
      { cz: "Praha patří mezi nejkrásnější města.", en: "Prague is among the most beautiful cities." },
      { cz: "Čeština patří mezi slovanské jazyky.", en: "Czech is among the Slavic languages." },
      { cz: "To může být pravda.", en: "That may be true." },
      { cz: "Přestěhoval jsem se do Prahy.", en: "I moved to Prague." },
      { cz: "Chci se přestěhovat.", en: "I want to move." }
    ],
    grammar: [
      { title: "Comparatives & Superlatives", note: "přátelský → přátelštější → nejpřátelštější (friendly → friendlier → friendliest). Examples: dobrý → lepší → nejlepší; vysoký → vyšší → nejvyšší; rychlý → rychlejší → nejrychlejší." },
      { title: "Patřit mezi (+ Accusative)", note: "= to be among. Praha patří mezi nejkrásnější města. Čeština patří mezi slovanské jazyky." },
      { title: "Více než", note: "= more than. více než rok; více než deset lidí; více než milion korun." },
      { title: "Může být", note: "může (can) + být (to be). To může být pravda / těžké / problém." },
      { title: "Reflexive verb: přestěhovat se", note: "The 'se' is essential. Přestěhoval jsem se do Prahy. Chci se přestěhovat." }
    ]
  },

  /* ---------------------------------------------------------- */
  {
    id: "lesson1hw",
    title: "Lesson 1 — Homework: Geography & State",
    emoji: "🗺️",
    vocab: [
      { cz: "krátký", en: "short", note: "adjective" },
      { cz: "zpráva", en: "news / report / message", note: "feminine" },
      { cz: "poslech", en: "listening", note: "masculine" },
      { cz: "povídat si", en: "to talk / chat", note: "reflexive verb" },
      { cz: "minulý rok", en: "last year", note: "time expression" },
      { cz: "přijít / přijet", en: "to come / arrive", note: "přijede = arrives (by transport)" },
      { cz: "vůči", en: "towards / toward", note: "preposition + dative" },
      { cz: "stát", en: "state / country", note: "masculine noun" },
      { cz: "skončit", en: "to finish / end / rank", note: "verb" },
      { cz: "první dojem", en: "first impression", note: "masculine" },
      { cz: "dojem", en: "impression", note: "masculine" },
      { cz: "překvapit", en: "to surprise", note: "verb" },
      { cz: "důležitý", en: "important", note: "adjective" },
      { cz: "člověk", en: "person / human being", note: "masculine" },
      { cz: "jiný", en: "different / another", note: "adjective" },
      { cz: "pomáhat", en: "to help", note: "verb" },
      { cz: "cítit se", en: "to feel", note: "reflexive verb" },
      { cz: "jako doma", en: "like at home", note: "expression" },
      { cz: "snadný", en: "easy", note: "adjective" },
      { cz: "proč", en: "why", note: "question word" },
      { cz: "doplnit", en: "to complete / fill in", note: "verb" },
      { cz: "vhodný", en: "suitable / appropriate", note: "adjective" },
      { cz: "slovo", en: "word", note: "neuter" },
      { cz: "správný", en: "correct / right", note: "adjective" },
      { cz: "tvar", en: "form / shape", note: "masculine" },
      { cz: "rozhodnout", en: "to decide", note: "verb" },
      { cz: "pravdivý", en: "true", note: "adjective" },
      { cz: "nepravdivý", en: "false / untrue", note: "adjective" },
      { cz: "získat", en: "to gain / obtain", note: "verb" },
      { cz: "přibližně", en: "approximately", note: "adverb" },
      { cz: "naopak", en: "on the contrary", note: "adverb" },
      { cz: "diskutovat", en: "to discuss", note: "verb" },
      { cz: "souhlasit", en: "to agree", note: "verb" },
      { cz: "spíše", en: "rather / more likely", note: "adverb" },
      { cz: "otevřený", en: "open", note: "adjective" },
      { cz: "rezervovaný", en: "reserved", note: "adjective" },
      { cz: "rada", en: "advice", note: "feminine" },
      { cz: "právě", en: "just / currently", note: "adverb" },
      { cz: "zeměpis", en: "geography", note: "masculine" },
      { cz: "sousedit s", en: "to border", note: "+ instrumental" },
      { cz: "hranice", en: "border", note: "feminine" },
      { cz: "tvořit", en: "to form", note: "verb" },
      { cz: "hora", en: "mountain", note: "feminine" },
      { cz: "řeka", en: "river", note: "feminine" },
      { cz: "délka", en: "length", note: "feminine" },
      { cz: "vzniknout", en: "to originate / be founded", note: "verb" },
      { cz: "státní zřízení", en: "system of government", note: "" },
      { cz: "prezident", en: "president", note: "masculine" },
      { cz: "vláda", en: "government", note: "feminine" },
      { cz: "parlament", en: "parliament", note: "masculine" },
      { cz: "schvalovat", en: "to approve", note: "verb" },
      { cz: "zákon", en: "law", note: "masculine" },
      { cz: "výkonná moc", en: "executive power", note: "" },
      { cz: "znak", en: "coat of arms / emblem", note: "" },
      { cz: "symbol", en: "symbol", note: "masculine" },
      { cz: "hymna", en: "national anthem", note: "feminine" },
      { cz: "skladatel", en: "composer", note: "masculine" },
      { cz: "výrobek", en: "product", note: "masculine" },
      { cz: "suvenýr", en: "souvenir", note: "masculine" },
      { cz: "značka", en: "brand", note: "feminine" },
      { cz: "vědec", en: "scientist", note: "masculine" },
      { cz: "vynalézt", en: "to invent", note: "irregular verb" },
      { cz: "státní vlajka", en: "national flag", note: "" },
      { cz: "poslanci", en: "deputies", note: "" },
      { cz: "projednávat", en: "to discuss", note: "" },
      { cz: "lev", en: "lion", note: "" },
      { cz: "lípa", en: "linden", note: "" },
      { cz: "píseň", en: "song", note: "" },
      { cz: "daleko", en: "far", note: "" },
      { cz: "zpívat", en: "to sing", note: "" },
      { cz: "slepý", en: "blind", note: "" },
      { cz: "hudebník", en: "musician", note: "" },
      { cz: "představení", en: "performance", note: "" },
      { cz: "obvykle", en: "usually", note: "" },
      { cz: "sklenice", en: "glass", note: "" },
      { cz: "šperky", en: "jewelry", note: "" },
      { cz: "ochutnat", en: "to taste", note: "" },
      { cz: "továrna", en: "factory", note: "" },
      { cz: "zakladatel", en: "founder", note: "" },
      { cz: "rozloha", en: "area", note: "" }
    ],
    phrases: [
      { cz: "Jaký byl váš první dojem?", en: "What was your first impression?" },
      { cz: "Můj první dojem byl velmi dobrý.", en: "My first impression was very good." },
      { cz: "V Praze se cítím jako doma.", en: "In Prague I feel at home." },
      { cz: "Podle mě je důležité učit se jazyk.", en: "In my opinion it is important to learn the language." },
      { cz: "Naučit se češtinu chvíli trvá.", en: "Learning Czech takes some time." },
      { cz: "Souhlasím s výsledky studie.", en: "I agree with the study results." },
      { cz: "Česko sousedí s Německem.", en: "The Czech Republic borders Germany." },
      { cz: "Pocházím z Turecka.", en: "I come from Turkey." },
      { cz: "Hora měří 1603 metrů.", en: "The mountain is 1,603 metres high." },
      { cz: "Hory tvoří hranici.", en: "The mountains form the border." }
    ],
    grammar: [
      { title: "s + Instrumental", note: "After verbs like sousedit (to border), mluvit (to speak with). Česko sousedí s Německem. Mluvím s kamarádem. Bydlím s rodiči." },
      { title: "pocházet z + Genitive", note: "Where someone/something comes from. Pocházím z Turecka. Pochází z Prahy. Víno pochází z Itálie." },
      { title: "měřit (height/length)", note: "Czech uses měřit where English says 'is ... high/long'. Hora měří 1603 metrů. Most měří 500 metrů." },
      { title: "tvořit", note: "to form / make up. Hory tvoří hranici. Les tvoří velkou část území. Parlament tvoří dvě komory." },
      { title: "Podle mě je důležité…", note: "= In my opinion it is important… Podle mě je důležité poznat nové lidi." }
    ]
  },

  /* ---------------------------------------------------------- */
  {
    id: "lesson2",
    title: "Lesson 2 — Culture, Ordinals & Word Families",
    emoji: "🎭",
    vocab: [
      { cz: "socha", en: "statue", note: "F" },
      { cz: "rozhledna", en: "lookout tower", note: "F" },
      { cz: "pomník", en: "monument", note: "M" },
      { cz: "kostel", en: "church", note: "M" },
      { cz: "klášter", en: "monastery", note: "M" },
      { cz: "věž", en: "tower", note: "F" },
      { cz: "řada", en: "row", note: "F" },
      { cz: "sedadlo", en: "seat", note: "N" },
      { cz: "jeviště", en: "stage", note: "N" },
      { cz: "básník", en: "poet", note: "M" },
      { cz: "báseň", en: "poem", note: "F" },
      { cz: "noty", en: "musical notes", note: "F, plural" },
      { cz: "hudební nástroje", en: "musical instruments", note: "M, plural" },
      { cz: "výstava", en: "exhibition", note: "F" },
      { cz: "hlediště", en: "auditorium / audience", note: "N" },
      { cz: "orchestr", en: "orchestra", note: "M" },
      { cz: "soutěž", en: "competition", note: "F" },
      { cz: "vyhrát", en: "to win", note: "nevyhrát = not win" },
      { cz: "citát", en: "quote", note: "M" },
      { cz: "hláška", en: "catchphrase (colloq.)", note: "F" },
      { cz: "spousta", en: "a lot of, plenty of", note: "F" },
      { cz: "používat", en: "to use", note: "" },
      { cz: "melodie", en: "melody", note: "F" },
      { cz: "ukradnout", en: "to steal", note: "ukradli = they stole" },
      { cz: "vědkyně", en: "scientist (female)", note: "F" },
      { cz: "nosit", en: "to carry / to wear", note: "habitual" },
      { cz: "materiál", en: "material", note: "M" },
      { cz: "vyrobit", en: "to make / manufacture", note: "" },
      { cz: "vynálezce", en: "inventor", note: "M" },
      { cz: "poradit", en: "to advise", note: "" },
      { cz: "žárovka", en: "light bulb", note: "F" },
      { cz: "založit", en: "to found / establish", note: "" },
      { cz: "výhra", en: "a win / victory", note: "F" },
      { cz: "krádež", en: "theft", note: "F" },
      { cz: "vynález", en: "invention", note: "M" },
      { cz: "skládat", en: "to compose", note: "" },
      { cz: "skladba", en: "composition", note: "F" }
    ],
    phrases: [
      { cz: "Vyhrál jsem soutěž ve zpěvu.", en: "I won a singing competition." },
      { cz: "Náš tým nevyhrál, ale hrál dobře.", en: "Our team didn't win, but played well." },
      { cz: "Znám hodně hlášek z filmů.", en: "I know a lot of movie catchphrases." },
      { cz: "Na party byla spousta lidí.", en: "There were a lot of people at the party." },
      { cz: "Ta melodie mi zní povědomě.", en: "That melody sounds familiar." },
      { cz: "Mozart byl slavný skladatel.", en: "Mozart was a famous composer." },
      { cz: "Edison byl slavný vynálezce.", en: "Edison was a famous inventor." },
      { cz: "Poradil mi, jak se učit lépe.", en: "He advised me on how to study better." },
      { cz: "Vyměnil jsem žárovku v kuchyni.", en: "I changed the light bulb in the kitchen." },
      { cz: "Založili novou firmu.", en: "They founded a new company." }
    ],
    grammar: [
      { title: "Ordinal Numbers 1–20, 30, 40", note: "1 první, 2 druhý, 3 třetí, 4 čtvrtý, 5 pátý, 6 šestý, 7 sedmý, 8 osmý, 9 devátý, 10 desátý, 11 jedenáctý, 12 dvanáctý, 13 třináctý, 14 čtrnáctý, 15 patnáctý, 16 šestnáctý, 17 sedmnáctý, 18 osmnáctý, 19 devatenáctý, 20 dvacátý, 30 třicátý, 40 čtyřicátý. 1st–4th & 7th are irregular; from 5th: cardinal stem + ý." },
      { title: "Irregular comparative/superlative adverbs", note: "dobře→líp/lépe→nejlíp/nejlépe; špatně→hůř/hůře→nejhůř; málo→míň/méně→nejmíň; moc→víc/více→nejvíc; daleko→dál/dále→nejdál; brzy→dřív/dříve→nejdřív; rád→raději→nejraději; dlouho→déle→nejdéle." },
      { title: "Registers (líp vs lépe)", note: "Short forms (líp, víc, míň, dál, hůř, dřív) = casual/spoken. -e forms (lépe, více, méně) = standard/written. Use -e in writing & formal speech." },
      { title: "Adjective vs adverb", note: "dobrý/lepší/nejlepší = adjective (describes a noun: dobrý film). dobře/líp/nejlíp = adverb (describes a verb: zpívá dobře)." },
      { title: "Word families (shared stems)", note: "vyhrát→výhra; ukradnout→krádež; vyrobit→výrobek/výroba; vynálezce→vynalézt→vynález; poradit→rada/poradce; založit→základ/základna; skladatel→skládat→skladba; básník→báseň→básnit." }
    ]
  },

  /* ---------------------------------------------------------- */
  {
    id: "lesson2hw",
    title: "Lesson 2 — Homework: Animals & Objects",
    emoji: "🐾",
    vocab: [
      { cz: "pes", en: "dog", note: "M — domestic" },
      { cz: "kočka", en: "cat", note: "F — domestic" },
      { cz: "králík", en: "rabbit", note: "M — domestic" },
      { cz: "kráva", en: "cow", note: "F — domestic" },
      { cz: "prase", en: "pig", note: "N — domestic" },
      { cz: "kůň", en: "horse", note: "M — domestic" },
      { cz: "ovce", en: "sheep", note: "F — domestic" },
      { cz: "koza", en: "goat", note: "F — domestic" },
      { cz: "medvěd", en: "bear", note: "M — wild" },
      { cz: "vlk", en: "wolf", note: "M — wild" },
      { cz: "liška", en: "fox", note: "F — wild" },
      { cz: "jelen", en: "deer", note: "M — wild" },
      { cz: "vydra", en: "otter", note: "F — wild" },
      { cz: "ježek", en: "hedgehog", note: "M — wild" },
      { cz: "lev", en: "lion", note: "M — exotic" },
      { cz: "tygr", en: "tiger", note: "M — exotic" },
      { cz: "slon", en: "elephant", note: "M — exotic" },
      { cz: "žirafa", en: "giraffe", note: "F — exotic" },
      { cz: "opice", en: "monkey", note: "F — exotic" },
      { cz: "zebra", en: "zebra", note: "F — exotic" },
      { cz: "hroch", en: "hippo", note: "M — exotic" },
      { cz: "krokodýl", en: "crocodile", note: "M — exotic" },
      { cz: "včela", en: "bee", note: "F — insect" },
      { cz: "motýl", en: "butterfly", note: "M — insect" },
      { cz: "pavouk", en: "spider", note: "M — arachnid" },
      { cz: "mravenec", en: "ant", note: "M — insect" },
      { cz: "moucha", en: "fly", note: "F — insect" },
      { cz: "ryba", en: "fish", note: "F — aquatic" },
      { cz: "žralok", en: "shark", note: "M — aquatic" },
      { cz: "velryba", en: "whale", note: "F — aquatic" },
      { cz: "delfín", en: "dolphin", note: "M — aquatic" },
      { cz: "krab", en: "crab", note: "M — aquatic" },
      { cz: "žába", en: "frog", note: "F — aquatic" },
      { cz: "orel", en: "eagle", note: "M — bird" },
      { cz: "sova", en: "owl", note: "F — bird" },
      { cz: "holub", en: "pigeon", note: "M — bird" },
      { cz: "kachna", en: "duck", note: "F — bird" },
      { cz: "slepice", en: "chicken", note: "F — bird" },
      { cz: "papoušek", en: "parrot", note: "M — bird" },
      { cz: "měsíc", en: "moon / month", note: "" },
      { cz: "otazník", en: "question mark", note: "" },
      { cz: "blesk", en: "lightning", note: "" },
      { cz: "pavučina", en: "spider web", note: "" },
      { cz: "strom", en: "tree", note: "" },
      { cz: "oko", en: "eye", note: "" },
      { cz: "duch", en: "ghost", note: "" },
      { cz: "hodiny", en: "clock", note: "" },
      { cz: "drak", en: "dragon / kite", note: "" },
      { cz: "barva", en: "colour", note: "" },
      { cz: "klaun", en: "clown", note: "" },
      { cz: "vykřičník", en: "exclamation mark", note: "" },
      { cz: "beruška", en: "ladybug", note: "" },
      { cz: "ruka", en: "hand / arm", note: "" },
      { cz: "tužka", en: "pencil", note: "" },
      { cz: "zámek", en: "castle / lock", note: "" },
      { cz: "lebka", en: "skull", note: "" },
      { cz: "kaktus", en: "cactus", note: "" },
      { cz: "sluneční brýle", en: "sunglasses", note: "" },
      { cz: "klíč", en: "key", note: "" },
      { cz: "srdce", en: "heart", note: "" },
      { cz: "sněhulák", en: "snowman", note: "" },
      { cz: "láhev", en: "bottle", note: "" },
      { cz: "kotva", en: "anchor", note: "" },
      { cz: "kladivo", en: "hammer", note: "" },
      { cz: "list", en: "leaf / sheet", note: "" },
      { cz: "želva", en: "turtle", note: "" },
      { cz: "terč", en: "target", note: "" },
      { cz: "rty", en: "lips", note: "" },
      { cz: "jetel", en: "clover", note: "" },
      { cz: "bomba", en: "bomb", note: "" },
      { cz: "stopka", en: "stem / stop sign", note: "" },
      { cz: "iglú", en: "igloo", note: "" },
      { cz: "dinosaurus", en: "dinosaur", note: "" }
    ],
    phrases: [],
    grammar: []
  },

  /* ---------------------------------------------------------- */
  {
    id: "lesson3",
    title: "Lesson 3 — Prepositions, Cases & Weather",
    emoji: "🌦️",
    vocab: [
      { cz: "hospoda", en: "pub", note: "F → v hospodě" },
      { cz: "diskotéka", en: "disco", note: "F → na diskotéce" },
      { cz: "nemocnice", en: "hospital", note: "F → v nemocnici" },
      { cz: "škola", en: "school", note: "F → ve škole" },
      { cz: "kino", en: "cinema", note: "N → v kině" },
      { cz: "divadlo", en: "theatre", note: "N → v divadle" },
      { cz: "restaurace", en: "restaurant", note: "F → v restauraci" },
      { cz: "kancelář", en: "office", note: "F → v kanceláři" },
      { cz: "nádraží", en: "train station", note: "→ na nádraží (exception)" },
      { cz: "letiště", en: "airport", note: "→ na letišti (exception)" },
      { cz: "konference", en: "conference", note: "→ na konferenci" },
      { cz: "koncert", en: "concert", note: "→ na koncertu" },
      { cz: "návštěva", en: "visit", note: "→ na návštěvě" },
      { cz: "holič", en: "barber", note: "M → u holiče" },
      { cz: "prší", en: "it's raining", note: "pršelo = it rained" },
      { cz: "sněží", en: "it's snowing", note: "sněžilo = it snowed" },
      { cz: "je hezky", en: "it's nice (weather)", note: "bylo hezky = it was nice" },
      { cz: "je teplo", en: "it's warm", note: "bylo teplo" },
      { cz: "je zima", en: "it's cold", note: "byla zima" },
      { cz: "je vítr", en: "it's windy", note: "byl vítr" },
      { cz: "ošklivo", en: "bad weather", note: "škaredě" },
      { cz: "zataženo", en: "overcast", note: "" },
      { cz: "slunečno", en: "sunny", note: "" },
      { cz: "stupňů", en: "degrees", note: "genitive plural of stupeň" },
      { cz: "právě", en: "right now / just", note: "" },
      { cz: "probíhat", en: "to take place", note: "probíhá výstava" },
      { cz: "areál", en: "premises / complex", note: "M" },
      { cz: "fanoušek", en: "fan", note: "M" },
      { cz: "prohlédnout si", en: "to view / look over", note: "reflexive" },
      { cz: "skutečný", en: "real / actual", note: "" },
      { cz: "kostým", en: "costume", note: "M" },
      { cz: "rekvizita", en: "prop", note: "F" },
      { cz: "použitý", en: "used", note: "" },
      { cz: "natáčení", en: "filming / shooting", note: "N" },
      { cz: "série", en: "series", note: "F" },
      { cz: "interaktivní", en: "interactive", note: "" },
      { cz: "návštěvník", en: "visitor", note: "M" },
      { cz: "vyzkoušet", en: "to try out", note: "" },
      { cz: "připravit", en: "to prepare", note: "" },
      { cz: "kouzelný", en: "magic / magical", note: "" },
      { cz: "lektvar", en: "potion", note: "M" },
      { cz: "navštívit", en: "to visit", note: "" },
      { cz: "putovní", en: "traveling / touring", note: "" },
      { cz: "omezený", en: "limited", note: "" },
      { cz: "doba", en: "period / time", note: "F" },
      { cz: "proto", en: "therefore / that's why", note: "" },
      { cz: "organizátor", en: "organizer", note: "M" },
      { cz: "očekávat", en: "to expect", note: "" }
    ],
    phrases: [
      { cz: "V Praze právě probíhá výstava.", en: "An exhibition is taking place in Prague right now." },
      { cz: "Fanoušci si mohou prohlédnout skutečné kostýmy.", en: "Fans can view real costumes." },
      { cz: "Mluvili jsme o kamarádovi.", en: "We talked about our friend." },
      { cz: "Dneska prší.", en: "It's raining today." },
      { cz: "Včera pršelo.", en: "It rained yesterday." },
      { cz: "Je teplo. Je plus 30 stupňů.", en: "It's warm. It's plus 30 degrees." },
      { cz: "Je zima. Je mínus 5 stupňů.", en: "It's cold. It's minus 5 degrees." },
      { cz: "Byl jsem u holiče.", en: "I was at the barber's." },
      { cz: "Tato putovní výstava už navštívila mnoho zemí.", en: "This travelling exhibition has already visited many countries." },
      { cz: "Jaké je počasí?", en: "What is the weather like?" }
    ],
    grammar: [
      { title: "Locative endings", note: "-u (hard masc.): v klubu, v hotelu, v parku. -i (soft fem.): na lekci, v práci, v restauraci. -e/-ě (fem. -a, neuter -o): ve škole, v kině, v divadle, v hospodě. -ce/-ze (velar shift k→c, h→z): v Praze, v bance, na diskotéce." },
      { title: "v/na vs u", note: "v/na + LOCATIVE = being in/at a place (v klubu, na koncertu). u + GENITIVE = at someone's place / visiting a person (u babičky, u doktora). Exceptions: na nádraží, na letišti." },
      { title: "Weather: today vs yesterday", note: "Present→past: Prší→Pršelo; Sněží→Sněžilo; Je hezky→Bylo hezky; Je zima→Byla zima; Je vítr→Byl vítr. Adverb-based always uses bylo; nouns agree in gender (zima→byla, vítr→byl)." },
      { title: "Jaké vs Jak", note: "Jaké je počasí? = What is it LIKE? → adjective agreeing with neuter: Je hezké/ošklivé. Jak je? = How is it? → short adverb form: Je teplo/chladno/ošklivo (exception: hezky)." },
      { title: "o + Locative (6th case)", note: "'o' (about) + locative. Masc. animate ending -ovi: Mluvili jsme o kamarádovi. natáčení filmů o Harrym Potterovi." }
    ]
  },

  /* ---------------------------------------------------------- */
  {
    id: "lesson4",
    title: "Lesson 4 — Past Tense & Knowing Verbs",
    emoji: "⏳",
    vocab: [
      { cz: "schůzka", en: "meetup / get-together", note: "F" },
      { cz: "uklidit", en: "to clean up", note: "perfective; uklízet = imperfective" },
      { cz: "byt", en: "apartment / flat", note: "M" },
      { cz: "guláš", en: "goulash", note: "M" },
      { cz: "závod", en: "race / competition event", note: "M" },
      { cz: "spisovatelka", en: "writer (female)", note: "F" },
      { cz: "narodit se", en: "to be born", note: "narodil(a) se" },
      { cz: "talentovaný", en: "talented", note: "" },
      { cz: "problém", en: "problem", note: "M" },
      { cz: "peníze", en: "money", note: "M, plural" },
      { cz: "syn", en: "son", note: "M" },
      { cz: "dcera", en: "daughter", note: "F" },
      { cz: "román", en: "novel", note: "M" },
      { cz: "povídka", en: "short story", note: "F" },
      { cz: "pohádka", en: "fairy tale", note: "F" },
      { cz: "próza", en: "prose", note: "F" },
      { cz: "umřít", en: "to die", note: "umřel(a)" },
      { cz: "filozof", en: "philosopher", note: "M" },
      { cz: "politik", en: "politician", note: "M" },
      { cz: "studovat", en: "to study", note: "" },
      { cz: "univerzita", en: "university", note: "F" },
      { cz: "profesor", en: "professor", note: "M" },
      { cz: "manželka", en: "wife", note: "F" },
      { cz: "přítel", en: "friend", note: "M" },
      { cz: "jezdit na koni", en: "to ride a horse", note: "" },
      { cz: "populární", en: "popular", note: "" },
      { cz: "sportovec", en: "athlete", note: "M" },
      { cz: "stejný", en: "same", note: "" },
      { cz: "zlatá medaile", en: "gold medal", note: "F" },
      { cz: "olympiáda", en: "the Olympics", note: "F" },
      { cz: "maraton", en: "marathon", note: "M" },
      { cz: "nejslavnější", en: "most famous", note: "" },
      { cz: "atlet", en: "athlete", note: "M" },
      { cz: "století", en: "century", note: "N" },
      { cz: "zpěvačka", en: "singer (female)", note: "F" },
      { cz: "lekce", en: "lesson", note: "F" },
      { cz: "festival", en: "festival", note: "M" },
      { cz: "lyžovat", en: "to ski", note: "" },
      { cz: "plavat", en: "to swim", note: "" },
      { cz: "tancovat", en: "to dance", note: "" },
      { cz: "vařit", en: "to cook", note: "" },
      { cz: "spát", en: "to sleep", note: "spal(a)" },
      { cz: "špagety", en: "spaghetti", note: "F, plural" },
      { cz: "čaj", en: "tea", note: "M" },
      { cz: "matematika", en: "mathematics", note: "F" },
      { cz: "nakupovat", en: "to shop / buy", note: "" },
      { cz: "oběd", en: "lunch", note: "M" },
      { cz: "počítač", en: "computer", note: "M" },
      { cz: "jídlo", en: "food", note: "N" },
      { cz: "pití", en: "drinks", note: "N" },
      { cz: "volno", en: "free time / day off", note: "N" },
      { cz: "výjimečně", en: "exceptionally", note: "" },
      { cz: "vstávat", en: "to get up", note: "imperfective" },
      { cz: "dívat se", en: "to watch / look at", note: "reflexive" },
      { cz: "plánovat", en: "to plan", note: "" },
      { cz: "připravovat", en: "to prepare", note: "imperfective" },
      { cz: "příští týden", en: "next week", note: "" },
      { cz: "omlouvat se", en: "to apologize", note: "reflexive" },
      { cz: "přijít", en: "to come / arrive", note: "" }
    ],
    phrases: [
      { cz: "Uklidil jsem byt.", en: "I cleaned the apartment. (male speaker)" },
      { cz: "Narodila jsem se v roce 1990.", en: "I was born in 1990. (female speaker)" },
      { cz: "Včera jsem uklidil byt.", en: "Yesterday I cleaned the apartment." },
      { cz: "Znám Prahu.", en: "I know Prague." },
      { cz: "Vím, kde je nádraží.", en: "I know where the train station is." },
      { cz: "Umím plavat.", en: "I can swim." },
      { cz: "Umím dobře vařit.", en: "I can cook well." },
      { cz: "Přijdu až v 8.", en: "I won't arrive until 8." },
      { cz: "Až budu v Praze, zavolám ti.", en: "When I'm in Prague, I'll call you." },
      { cz: "Díval jsem se na televizi.", en: "I watched television." }
    ],
    grammar: [
      { title: "Past tense formation", note: "L-participle (stem + -l) + auxiliary jsem/jsi/jsme/jste (1st & 2nd person; 3rd person has none). Agrees with subject: -l (masc sg), -la (fem sg), -lo (neut sg), -li (masc/mixed pl), -ly (fem pl). Dělal jsem / Dělala jsem / Dělali jsme." },
      { title: "Position of jsem & se (clitics)", note: "jsem/jsi and reflexive se/si go in SECOND position (after first stressed word). Order is jsem + se: Narodila jsem se (not 'Narodila se jsem'). Včera jsem uklidil byt." },
      { title: "Irregular past-tense verbs", note: "moct→mohl; být→byl; číst→četl; mít→měl; psát→psal; jít→šel/šla; chtít→chtěl; jíst→jedl. Must be memorized." },
      { title: "znát vs vědět vs umět", note: "znát + object = know a person/place/thing (Znám Prahu). vědět + clause = know a fact (Vím, kde je nádraží). umět + infinitive/skill = know how to (Umím plavat)." },
      { title: "Versatile 'až'", note: "not until (Přijdu až v 8), until (Čekej, až přijdu), when-future (Až budu v Praze…), as far as (Jeli jsme až do Prahy), as much as (Čekali jsme až tři hodiny). It pushes something further in time/distance/amount." },
      { title: "Reflexive verbs — SE vs SI", note: "SE (accusative): jmenovat se, dívat se, smát se, bát se, ptát se, učit se, narodit se, cítit se, těšit se. SI (dative, for oneself): myslet si, přát si, dát si, vzít si, všimnout si." }
    ]
  },

  /* ---------------------------------------------------------- */
  {
    id: "lesson5",
    title: "Lesson 5 — Time, Days, Months & Modals",
    emoji: "🕐",
    vocab: [
      { cz: "ráno", en: "morning", note: "" },
      { cz: "dopoledne", en: "before noon / late morning", note: "" },
      { cz: "v poledne", en: "at noon", note: "" },
      { cz: "odpoledne", en: "afternoon", note: "" },
      { cz: "večer", en: "evening", note: "" },
      { cz: "v noci", en: "at night", note: "" },
      { cz: "v pondělí", en: "on Monday", note: "" },
      { cz: "v úterý", en: "on Tuesday", note: "" },
      { cz: "ve středu", en: "on Wednesday", note: "ve (st- cluster)" },
      { cz: "ve čtvrtek", en: "on Thursday", note: "ve (čt- cluster)" },
      { cz: "v pátek", en: "on Friday", note: "" },
      { cz: "v sobotu", en: "on Saturday", note: "" },
      { cz: "v neděli", en: "on Sunday", note: "" },
      { cz: "leden", en: "January", note: "M — 1. ledna" },
      { cz: "únor", en: "February", note: "M — 1. února" },
      { cz: "březen", en: "March", note: "M — 1. března" },
      { cz: "duben", en: "April", note: "M — 1. dubna" },
      { cz: "květen", en: "May", note: "M — 1. května" },
      { cz: "červen", en: "June", note: "M — 1. června" },
      { cz: "červenec", en: "July", note: "M — 1. července" },
      { cz: "srpen", en: "August", note: "M — 1. srpna" },
      { cz: "září", en: "September", note: "N — indeclinable; 1. září" },
      { cz: "říjen", en: "October", note: "M — 1. října" },
      { cz: "listopad", en: "November", note: "M — 1. listopadu" },
      { cz: "prosinec", en: "December", note: "M — 1. prosince" },
      { cz: "moct", en: "can / to be able to", note: "můžu, můžeš, může" },
      { cz: "muset", en: "must / to have to", note: "musím, musíš, musí" },
      { cz: "nechtít", en: "to not want", note: "nechceš = you don't want" },
      { cz: "mít čas", en: "to have time", note: "" },
      { cz: "sejít se", en: "to meet up", note: "reflexive; sejdeme se" },
      { cz: "hodit se", en: "to suit / to work (for someone)", note: "Hodí se ti to?" },
      { cz: "třeba", en: "maybe / for instance", note: "" },
      { cz: "objevit", en: "to discover", note: "objevovat = imperfective" },
      { cz: "výběrová káva", en: "specialty coffee", note: "F" },
      { cz: "stále častěji", en: "increasingly / more and more often", note: "" },
      { cz: "vybírat si", en: "to choose / select", note: "reflexive" },
      { cz: "kvalitnější", en: "higher quality", note: "comparative" },
      { cz: "zrno", en: "grain / bean", note: "N" },
      { cz: "růst", en: "to grow / rise", note: "roste = grows" },
      { cz: "zájem", en: "interest", note: "M" },
      { cz: "takzvaný", en: "so-called", note: "" },
      { cz: "známý původ", en: "known origin", note: "" },
      { cz: "oblíbený", en: "popular / favorite", note: "" },
      { cz: "nápoj", en: "drink / beverage", note: "M" },
      { cz: "filtrovaná káva", en: "filtered coffee", note: "F" },
      { cz: "kavárna", en: "cafe", note: "F" },
      { cz: "kávovar", en: "coffee maker", note: "M" },
      { cz: "barista", en: "barista", note: "M" },
      { cz: "odborník", en: "expert", note: "M" },
      { cz: "koníček", en: "hobby", note: "M" },
      { cz: "zážitek", en: "experience", note: "M" },
      { cz: "pražírna", en: "roastery", note: "F" }
    ],
    phrases: [
      { cz: "Nechceš jít na tenis?", en: "Don't you want to go play tennis?" },
      { cz: "Dneska nemůžu. Nemám čas, musím pracovat.", en: "Today I can't. I don't have time, I have to work." },
      { cz: "Můžeš zítra odpoledne?", en: "Can you tomorrow afternoon?" },
      { cz: "Kdy se sejdeme?", en: "When shall we meet?" },
      { cz: "Hodí se ti to?", en: "Does that work for you?" },
      { cz: "Těším se!", en: "I'm looking forward to it!" },
      { cz: "Češi objevují výběrovou kávu.", en: "Czechs are discovering specialty coffee." },
      { cz: "Roste zájem o výběrovou kávu.", en: "Interest in specialty coffee is growing." },
      { cz: "Kávu dnes lidé pijí nejen v kavárnách, ale také doma.", en: "Today people drink coffee not only in cafes, but also at home." },
      { cz: "Třicátého května jsem se narodil.", en: "I was born on the 30th of May." }
    ],
    grammar: [
      { title: "v vs ve", note: "Use 've' before tricky consonant clusters (v-, f-, dv-, tv-, st-, čt-): ve středu, ve čtvrtek, ve dvě, ve dvanáct. Otherwise 'v': v pátek, v sobotu, v pondělí, v jednu, v šest. 'v dvanáct' is WRONG → ve dvanáct." },
      { title: "Telling time (v + number)", note: "v jednu (at 1), ve dvě (at 2), v šest (at 6), v deset (at 10), v jedenáct (at 11), ve dvanáct (at 12)." },
      { title: "Dates use genitive", note: "'1st of ___' uses genitive month: 1. ledna, 1. února, 1. května, 1. září. Dates don't need 'v': třicátého května jsem se narodil (not 'v třicátý')." },
      { title: "Months gender", note: "All months are masculine EXCEPT září (September) = neuter. Září is indeclinable: same in nominative and genitive (1. září)." },
      { title: "Modal verbs moct / muset", note: "moct (can): můžu, můžeš, může. muset (must): musím, musíš, musí. Both take an infinitive: Musím pracovat. Můžu přijít." },
      { title: "jít na vs jít do", note: "jít na + accusative = go for an activity/refreshment (jít na kávu, na pivo, na večeři). jít do + genitive = go to an enclosed place/building (jít do restaurace, do kina, do práce, do školy)." }
    ]
  },

  /* ---------------------------------------------------------- */
  {
    id: "lesson6",
    title: "Lesson 6 — Family, Possessives & Describing People",
    emoji: "👨‍👩‍👧",
    vocab: [
      { cz: "tatínek", en: "dad", note: "M" },
      { cz: "maminka", en: "mum", note: "F" },
      { cz: "bratr", en: "brother", note: "M" },
      { cz: "sestra", en: "sister", note: "F" },
      { cz: "syn", en: "son", note: "M" },
      { cz: "dcera", en: "daughter", note: "F" },
      { cz: "dědeček", en: "grandfather", note: "M" },
      { cz: "babička", en: "grandmother", note: "F" },
      { cz: "vnuk", en: "grandson", note: "M" },
      { cz: "vnučka", en: "granddaughter", note: "F" },
      { cz: "manžel", en: "husband", note: "M" },
      { cz: "manželka", en: "wife", note: "F" },
      { cz: "švagr", en: "brother-in-law", note: "M" },
      { cz: "přítel", en: "boyfriend / (male) friend", note: "M" },
      { cz: "přítelkyně", en: "girlfriend / (female) friend", note: "F" },
      { cz: "rodina", en: "family", note: "F" },
      { cz: "rodiče", en: "parents", note: "M pl." },
      { cz: "děti", en: "children", note: "pl." },
      { cz: "dítě", en: "child", note: "N" },
      { cz: "svobodný", en: "single (unmarried)", note: "svobodná (F)" },
      { cz: "vdaná", en: "married (woman)", note: "F" },
      { cz: "ženatý", en: "married (man)", note: "M" },
      { cz: "automechanik", en: "car mechanic", note: "M" },
      { cz: "ekonom", en: "economist", note: "M" },
      { cz: "doktorka", en: "doctor (female)", note: "F" },
      { cz: "student", en: "student", note: "studentka (F)" },
      { cz: "firma", en: "company / firm", note: "F" },
      { cz: "v domácnosti", en: "a homemaker (at home)", note: "" },
      { cz: "medicína", en: "medicine (subject)", note: "F" },
      { cz: "matematika", en: "mathematics", note: "F" },
      { cz: "inteligentní", en: "intelligent", note: "" },
      { cz: "prostě", en: "simply / just", note: "" },
      { cz: "fantastický", en: "fantastic", note: "" },
      { cz: "nejlepší", en: "best", note: "" },
      { cz: "fajn", en: "nice / cool", note: "colloquial" },
      { cz: "mladý", en: "young", note: "opp. starý" },
      { cz: "starý", en: "old", note: "opp. mladý / nový" },
      { cz: "nový", en: "new", note: "opp. starý" },
      { cz: "malý", en: "small", note: "opp. velký" },
      { cz: "velký", en: "big / large", note: "opp. malý" },
      { cz: "vysoký", en: "tall / high", note: "opp. malý / nízký" },
      { cz: "hezký", en: "pretty / nice", note: "opp. ošklivý" },
      { cz: "krásný", en: "beautiful", note: "opp. ošklivý" },
      { cz: "ošklivý", en: "ugly", note: "opp. hezký" },
      { cz: "hodný", en: "kind / good (person)", note: "opp. zlý" },
      { cz: "zlý", en: "bad / mean / wicked", note: "opp. hodný" },
      { cz: "šťastný", en: "happy", note: "opp. smutný" },
      { cz: "smutný", en: "sad", note: "opp. šťastný" },
      { cz: "zdravý", en: "healthy", note: "opp. nemocný" },
      { cz: "nemocný", en: "sick / ill", note: "opp. zdravý" },
      { cz: "tlustý", en: "fat", note: "opp. hubený" },
      { cz: "hubený", en: "thin / skinny", note: "opp. tlustý" },
      { cz: "oběť", en: "victim", note: "F" },
      { cz: "připomínat si", en: "to commemorate / remember", note: "" },
      { cz: "věnovaný", en: "dedicated (to)", note: "" },
      { cz: "trpět", en: "to suffer", note: "" },
      { cz: "zemřít", en: "to die", note: "" },
      { cz: "kvůli", en: "because of / due to", note: "+ dative" },
      { cz: "totalitní režim", en: "totalitarian regime", note: "M" },
      { cz: "století", en: "century", note: "N" },
      { cz: "datum", en: "date", note: "N" },
      { cz: "podpis", en: "signature / signing", note: "M" },
      { cz: "výstava", en: "exhibition", note: "F" },
      { cz: "přednáška", en: "lecture", note: "F" },
      { cz: "historie", en: "history", note: "F" },
      { cz: "cíl", en: "goal / aim", note: "M" },
      { cz: "minulost", en: "the past", note: "F" },
      { cz: "upozornit", en: "to point out / draw attention to", note: "na + acc." },
      { cz: "význam", en: "meaning / importance", note: "M" },
      { cz: "svoboda", en: "freedom", note: "F" },
      { cz: "demokracie", en: "democracy", note: "F" },
      { cz: "ochrana", en: "protection", note: "F" },
      { cz: "lidská práva", en: "human rights", note: "N pl." },
      { cz: "tragédie", en: "tragedy", note: "F" },
      { cz: "opakovat se", en: "to repeat / happen again", note: "" }
    ],
    phrases: [
      { cz: "To je moje rodina.", en: "This is my family." },
      { cz: "Mám staršího bratra a mladší sestru.", en: "I have an older brother and a younger sister." },
      { cz: "Kolik ti je? – Je mi 25.", en: "How old are you? – I'm 25." },
      { cz: "Můj tatínek se jmenuje Adam. Je mu 50 let.", en: "My dad is called Adam. He is 50." },
      { cz: "Moje maminka nepracuje, je v domácnosti.", en: "My mum doesn't work, she's a homemaker." },
      { cz: "Je vdaná, ale ještě nemá děti.", en: "She is married, but doesn't have children yet." },
      { cz: "Petr je moc hezký a inteligentní.", en: "Petr is very handsome and intelligent." },
      { cz: "To je moje nejlepší kamarádka.", en: "This is my best friend (female)." },
      { cz: "Jaká je tvoje přítelkyně? – Je moc hodná.", en: "What is your girlfriend like? – She's very kind." },
      { cz: "Každý rok 23. srpna si Evropa připomíná oběti stalinismu a nacismu.", en: "Every year on August 23rd Europe commemorates the victims of Stalinism and Nazism." }
    ],
    grammar: [
      { title: "Possessive pronouns", note: "Agree with the gender of the thing owned. já: můj (M) / moje-má (F,N); ty: tvůj / tvoje-tvá; my: náš / naše; vy: váš / vaše. 3rd person is invariable: jeho (his), její (her), jejich (their) — never change." },
      { title: "Possessive adjectives from names", note: "Masculine owner: -ův/-ova/-ovo (Adamův syn, Adamova dcera). Feminine owner: -in/-ina/-ino (Janin syn, Janina kočka). Ending agrees with the thing owned." },
      { title: "Accusative case (object)", note: "After mít / hledat, the object goes to accusative; adjective + noun agree. M animate: -a/-ého (Hledám staršího bratra). F: -ou/-u (Mám malou dceru). N & M inanimate: like nominative." },
      { title: "Adjective gender agreement", note: "Hard adjectives: masc -ý, fem -á, neuter -é (jaký/jaká/jaké; hodný/hodná/hodné; zdravý/zdravá/zdravé). Naše dcera už je zdravá." },
      { title: "Expressing age (dative)", note: "Czech doesn't say 'I am 25' — it uses dative: 'to me is 25'. Verb stays je; pronoun changes: mi (me), ti (you), mu (him), jí (her). Je mi 25. Je mu 50 let. Je jí 26 let." }
    ]
  },

  /* ---------------------------------------------------------- */
  {
    id: "lesson7",
    title: "Lesson 7 — In the Restaurant & Food",
    emoji: "🍽️",
    vocab: [
      { cz: "dát si", en: "to have / to order", note: "reflexive; Dám si…" },
      { cz: "k pití", en: "for drinking", note: "k + dative" },
      { cz: "k jídlu", en: "for eating", note: "k + dative" },
      { cz: "jednou", en: "once / one portion", note: "irregular" },
      { cz: "dvakrát", en: "twice / two portions", note: "" },
      { cz: "třikrát", en: "three times / three portions", note: "" },
      { cz: "čtyřikrát", en: "four times / four portions", note: "" },
      { cz: "česneková polévka", en: "garlic soup", note: "F" },
      { cz: "bramborová polévka", en: "potato soup", note: "F" },
      { cz: "gulášová polévka", en: "goulash soup", note: "F" },
      { cz: "rajčatová polévka", en: "tomato soup", note: "F" },
      { cz: "pečené kuře", en: "roast chicken", note: "" },
      { cz: "vařené brambory", en: "boiled potatoes", note: "" },
      { cz: "vepřové maso", en: "pork", note: "" },
      { cz: "dušená rýže", en: "steamed rice", note: "" },
      { cz: "hovězí maso", en: "beef", note: "" },
      { cz: "dušená zelenina", en: "steamed vegetables", note: "" },
      { cz: "smažený řízek", en: "fried schnitzel", note: "" },
      { cz: "bramborový salát", en: "potato salad", note: "" },
      { cz: "smažený sýr", en: "fried cheese", note: "" },
      { cz: "hranolky", en: "fries", note: "" },
      { cz: "tatarská omáčka", en: "tartar sauce", note: "" },
      { cz: "maďarský guláš", en: "Hungarian goulash", note: "" },
      { cz: "houskové knedlíky", en: "bread dumplings", note: "" },
      { cz: "zeleninový salát", en: "vegetable salad", note: "" },
      { cz: "šopský salát", en: "shopska salad", note: "tomato, cucumber, feta" },
      { cz: "čokoládový dort", en: "chocolate cake", note: "" },
      { cz: "čokoládová zmrzlina", en: "chocolate ice cream", note: "" },
      { cz: "vanilková zmrzlina", en: "vanilla ice cream", note: "" },
      { cz: "palačinky s karamelem", en: "pancakes with caramel", note: "" },
      { cz: "banán s čokoládou", en: "banana with chocolate", note: "" },
      { cz: "neperlivá voda", en: "still water", note: "F" },
      { cz: "perlivá voda", en: "sparkling water", note: "F" },
      { cz: "pomerančový džus", en: "orange juice", note: "" },
      { cz: "zelený čaj", en: "green tea", note: "" },
      { cz: "černý čaj", en: "black tea", note: "" },
      { cz: "kola", en: "cola", note: "F" },
      { cz: "světlé pivo", en: "light / pale beer", note: "" },
      { cz: "černé pivo", en: "dark beer", note: "" },
      { cz: "bílé víno", en: "white wine", note: "" },
      { cz: "červené víno", en: "red wine", note: "" },
      { cz: "kuře", en: "chicken", note: "N — tricky gender!" },
      { cz: "rýže", en: "rice", note: "F — tricky gender!" },
      { cz: "zaplatit", en: "to pay", note: "Zaplatím = I'll pay / the bill" },
      { cz: "koruna", en: "crown (Czech currency Kč)", note: "F" },
      { cz: "ujde to", en: "it's okay / so-so", note: "modest 'I'm alright'" },
      { cz: "později", en: "later", note: "" },
      { cz: "možná", en: "maybe / perhaps", note: "" },
      { cz: "vegetarián", en: "vegetarian", note: "M" },
      { cz: "toaleta", en: "toilet", note: "F" },
      { cz: "škoda", en: "a pity / a shame", note: "To je škoda." },
      { cz: "bohužel", en: "unfortunately", note: "" },
      { cz: "pomoct", en: "to help", note: "" },
      { cz: "přesto", en: "nevertheless / and yet", note: "" },
      { cz: "méně", en: "less", note: "" },
      { cz: "spotřeba", en: "consumption", note: "F" },
      { cz: "sportovat", en: "to do sport", note: "" },
      { cz: "životní styl", en: "lifestyle", note: "M" },
      { cz: "nealkoholické pivo", en: "non-alcoholic beer", note: "N" },
      { cz: "pandemie", en: "pandemic", note: "F" },
      { cz: "raději", en: "rather / preferably", note: "" },
      { cz: "tradiční", en: "traditional", note: "" },
      { cz: "ztrácet", en: "to lose", note: "" },
      { cz: "scházet se", en: "to meet / gather", note: "s + instrumental" },
      { cz: "trávit čas", en: "to spend time", note: "" },
      { cz: "společně", en: "together", note: "" },
      { cz: "hlavně", en: "mainly / above all", note: "" },
      { cz: "příjemný", en: "pleasant", note: "" },
      { cz: "atmosféra", en: "atmosphere", note: "F" }
    ],
    phrases: [
      { cz: "Co si dáte k pití?", en: "What will you have to drink?" },
      { cz: "Dám si neperlivou vodu.", en: "I'll have still water." },
      { cz: "Dám si pečené kuře a brambory.", en: "I'll have roast chicken and potatoes." },
      { cz: "Dáte si dezert nebo kávu?", en: "Will you have dessert or coffee?" },
      { cz: "To je všechno? – Ano, zaplatím.", en: "Is that all? – Yes, I'll pay." },
      { cz: "Zvlášť, nebo dohromady?", en: "Separately, or together?" },
      { cz: "Nejím maso. Jsem vegetarián.", en: "I don't eat meat. I'm a vegetarian." },
      { cz: "Kde je tady toaleta?", en: "Where is the toilet here?" },
      { cz: "Už musím jít. Na shledanou.", en: "I have to go now. Goodbye." },
      { cz: "V Česku se pije méně piva než dříve.", en: "In Czechia people drink less beer than before." }
    ],
    grammar: [
      { title: "Ordering with dát si", note: "dát si (lit. 'give oneself') = to have/order; always keeps 'si'; the item goes to accusative. Dám si… (I'll have), Dáš si…? (informal), Dáte si…? (formal). Dám si pečené kuře." },
      { title: "k + dative (purpose)", note: "k (ke/ku before some consonants) = 'for/to a purpose', takes dative. Co si dáte k pití? (for drinking). A co k jídlu? (for eating)." },
      { title: "Counting portions", note: "Multiplicative adverbs are invariable, so the food word doesn't change: jednou (once), dvakrát, třikrát, čtyřikrát. Dvakrát pivo. Třikrát kávu, prosím." },
      { title: "Demonstratives ten / ta / to / ty", note: "ten (M), ta (F), to (N), ty (plural) = 'that/the'; adjective agrees (-ý/-á/-é/-é). Ten čaj je dobrý. Ta rýže je dobrá. To pivo je dobré. Ty knedlíky jsou dobré." },
      { title: "Tricky genders", note: "kuře (chicken) is NEUTER → To kuře je dobré. rýže (rice) is FEMININE → Ta rýže je dobrá. Memorise these separately." }
    ]
  },

  /* ---------------------------------------------------------- */
  {
    id: "lesson8",
    title: "Lesson 8 — Future Tense & Going Places",
    emoji: "✈️",
    vocab: [
      { cz: "půjdu", en: "I'll go (on foot)", note: "jít → future" },
      { cz: "pojedu", en: "I'll go (by vehicle)", note: "jet → future" },
      { cz: "poletím", en: "I'll fly", note: "letět → future" },
      { cz: "jezdit na bruslích", en: "to (go) ice-skate", note: "" },
      { cz: "jezdit na kole", en: "to ride a bike / cycle", note: "" },
      { cz: "jít na procházku", en: "to go for a walk", note: "" },
      { cz: "luštit křížovku", en: "to do a crossword", note: "" },
      { cz: "chytat ryby", en: "to catch fish / to fish", note: "rybařit" },
      { cz: "opalovat se", en: "to sunbathe", note: "reflexive" },
      { cz: "hrát karty", en: "to play cards", note: "" },
      { cz: "hrát na kytaru", en: "to play the guitar", note: "" },
      { cz: "fotografovat", en: "to take photos", note: "fotit" },
      { cz: "skládat puzzle", en: "to do a jigsaw puzzle", note: "" },
      { cz: "plést", en: "to knit", note: "" },
      { cz: "vyrábět", en: "to make / craft", note: "" },
      { cz: "odpočívat", en: "to rest / relax", note: "" },
      { cz: "letiště", en: "airport", note: "N — na letiště" },
      { cz: "nádraží", en: "(train) station", note: "N — na nádraží" },
      { cz: "galerie", en: "gallery", note: "F — do galerie" },
      { cz: "koncert", en: "concert", note: "M — na koncert" },
      { cz: "klub", en: "club", note: "M — do klubu" },
      { cz: "park", en: "park", note: "M — do parku" },
      { cz: "banka", en: "bank", note: "F — do banky" },
      { cz: "obchod", en: "shop", note: "M — do obchodu" },
      { cz: "supermarket", en: "supermarket", note: "M — do supermarketu" },
      { cz: "fitko", en: "gym", note: "N — do fitka" },
      { cz: "hory", en: "mountains", note: "F pl. — na hory" },
      { cz: "moře", en: "sea", note: "N — k moři" },
      { cz: "dovolená", en: "holiday / vacation", note: "F — na dovolenou" },
      { cz: "výlet", en: "trip / excursion", note: "M — na výlet" },
      { cz: "ambasáda", en: "embassy", note: "F — na ambasádu" },
      { cz: "jóga", en: "yoga", note: "F — na jógu" },
      { cz: "miláček", en: "darling / sweetheart", note: "miláčku (vocative)" },
      { cz: "ředitelka", en: "director / principal (female)", note: "ředitel (M)" },
      { cz: "konference", en: "conference", note: "F" },
      { cz: "lingvistický", en: "linguistic", note: "" },
      { cz: "přednáška", en: "lecture", note: "F" },
      { cz: "moderovat", en: "to moderate / host", note: "" },
      { cz: "připravovat", en: "to prepare", note: "" },
      { cz: "slíbit", en: "to promise", note: "perfective" },
      { cz: "ochutnat", en: "to taste / try (food)", note: "" },
      { cz: "specialita", en: "speciality (dish)", note: "F" },
      { cz: "svíčková s knedlíky", en: "svíčková (beef in cream sauce) with dumplings", note: "" },
      { cz: "zvát", en: "to invite", note: "zve = invites" },
      { cz: "večeře", en: "dinner", note: "F" },
      { cz: "tancovat", en: "to dance", note: "" },
      { cz: "zůstat", en: "to stay", note: "perfective" },
      { cz: "dostat", en: "to get / receive", note: "perfective" },
      { cz: "vstávat", en: "to get up", note: "" },
      { cz: "o víkendu", en: "at the weekend", note: "" },
      { cz: "volno", en: "time off / free time", note: "N" },
      { cz: "pohoda", en: "chill / all good", note: "F, colloquial" },
      { cz: "naštěstí", en: "luckily / fortunately", note: "" },
      { cz: "dopadnout", en: "to turn out", note: "perfective; dopadlo dobře" },
      { cz: "zkouška", en: "exam", note: "F" },
      { cz: "těžký", en: "hard / difficult", note: "also 'heavy'" },
      { cz: "zajímavý", en: "interesting", note: "" },
      { cz: "lístek", en: "ticket", note: "M; lístky (pl.)" },
      { cz: "muzikál", en: "musical", note: "M" },
      { cz: "program", en: "schedule / programme", note: "M" },
      { cz: "unavený", en: "tired", note: "" },
      { cz: "cvičit", en: "to exercise / work out", note: "" },
      { cz: "obraz", en: "painting", note: "M; obrazy (pl.)" }
    ],
    phrases: [
      { cz: "Co budeš dneska dělat?", en: "What will you be doing today?" },
      { cz: "Zavolám ti večer.", en: "I'll call you in the evening." },
      { cz: "Půjdu do kina.", en: "I'll go to the cinema (on foot)." },
      { cz: "Pojedu na letiště.", en: "I'll go to the airport (by vehicle)." },
      { cz: "Zítra večer poletí na Floridu.", en: "Tomorrow evening he'll fly to Florida." },
      { cz: "O víkendu pojedeme na výlet.", en: "At the weekend we'll go on a trip." },
      { cz: "Půjdu na návštěvu ke kamarádce.", en: "I'll go to visit a friend (female)." },
      { cz: "O víkendu budu mít volno.", en: "At the weekend I'll have time off." },
      { cz: "Nechceš jít do divadla?", en: "Don't you want to go to the theatre?" },
      { cz: "Měj se hezky!", en: "Take care! / Have a nice time!" }
    ],
    grammar: [
      { title: "Future 1: budu + infinitive", note: "For ongoing/repeated actions, use future of být (budu, budeš, bude, budeme, budete, budou) + imperfective infinitive. Budu spát a odpočívat. Budeme mluvit o práci." },
      { title: "Future 2: perfective present", note: "For a single completed future action, the perfective verb's present form already means the future — do NOT add 'budu'. Zavolám ti (not 'budu zavolat'). Dám si kávu." },
      { title: "Going: půjdu / pojedu / poletím", note: "Czech picks the 'go' verb by mode: jít→půjdu (on foot), jet→pojedu (by vehicle), letět→poletím (by air). All are perfective and mean the future. Půjdu do školy. Pojedu na nákup." },
      { title: "kde? vs kam?", note: "kde? = static location → v/na/u + locative (Jsem doma. Byl jsem v kině). kam? = direction → do/na/k + case, or domů (Jdu domů. Šli jsme do kina)." },
      { title: "Direction: do / na / k(e)", note: "do + genitive = into buildings (do kina, do školy). na + accusative = events/activities/open places (na oběd, na výlet, na hory, na nádraží). k/ke + dative = to a PERSON (ke kamarádovi, k doktorovi)." }
    ]
  }
];

/* =============================================================
   GRAMMAR EXERCISES
   -------------------------------------------------------------
   Each item:
     lessonId  - which lesson it belongs to (for filtering)
     type      - "mc" (multiple choice) or "blank" (fill-in)
     q         - the question / sentence (use ___ for the blank)
     a         - the correct answer
     options   - choices (mc only; the correct one is included)
     hint      - optional short explanation shown after answering
   To add more: copy a line, change the fields. That's it.
   ============================================================= */
const GRAMMAR_EXERCISES = [
  // ---- Lesson 1: comparatives, patřit mezi, více než ----
  { lessonId: "lesson1", type: "mc", q: "dobrý → ___ → nejlepší", a: "lepší", options: ["lepší", "dobřejší", "nejdobrý", "více dobrý"], hint: "Irregular: dobrý → lepší → nejlepší." },
  { lessonId: "lesson1", type: "mc", q: "vysoký → ___ → nejvyšší", a: "vyšší", options: ["vyšší", "vysokejší", "více vysoký", "nejvysoký"], hint: "vysoký → vyšší → nejvyšší." },
  { lessonId: "lesson1", type: "mc", q: "přátelský → přátelštější → ___", a: "nejpřátelštější", options: ["nejpřátelštější", "nejpřátelský", "přátelštějí", "více přátelský"], hint: "Superlative always takes nej-." },
  { lessonId: "lesson1", type: "blank", q: "Praha ___ mezi nejkrásnější města. (belongs among)", a: "patří", hint: "patřit mezi = to be among (+ Accusative)." },
  { lessonId: "lesson1", type: "blank", q: "V Česku žije ___ než jeden milion cizinců. (more)", a: "více", hint: "více než = more than." },

  // ---- Lesson 1 homework: cases & prepositions ----
  { lessonId: "lesson1hw", type: "mc", q: "Pocházím ___ Turecka.", a: "z", options: ["z", "s", "v", "u"], hint: "pocházet z + Genitive (come from)." },
  { lessonId: "lesson1hw", type: "mc", q: "Česko sousedí ___ Německem.", a: "s", options: ["s", "z", "na", "o"], hint: "sousedit s + Instrumental (to border)." },
  { lessonId: "lesson1hw", type: "mc", q: "Mluvím ___ kamarádem.", a: "s", options: ["s", "z", "o", "u"], hint: "s + Instrumental = with." },
  { lessonId: "lesson1hw", type: "blank", q: "Hora ___ 1603 metrů. (is ... high — 'to measure')", a: "měří", hint: "Czech uses měřit for height/length." },
  { lessonId: "lesson1hw", type: "blank", q: "Hory ___ hranici. (form)", a: "tvoří", hint: "tvořit = to form / make up." },

  // ---- Lesson 2: ordinals, comparative adverbs ----
  { lessonId: "lesson2", type: "mc", q: "8 (eighth) = ___", a: "osmý", options: ["osmý", "osmnáctý", "osumý", "osmnád"], hint: "osmý = 8th (irregular-ish)." },
  { lessonId: "lesson2", type: "mc", q: "5 (fifth) = ___", a: "pátý", options: ["pátý", "pětý", "patnáctý", "pětinásobný"], hint: "pátý = 5th." },
  { lessonId: "lesson2", type: "mc", q: "20 (twentieth) = ___", a: "dvacátý", options: ["dvacátý", "dvanáctý", "dvacet", "dvojitý"], hint: "dvacátý = 20th (multiples of ten use -cátý)." },
  { lessonId: "lesson2", type: "mc", q: "dobře → líp → ___ (adverb: best)", a: "nejlíp", options: ["nejlíp", "nejlepší", "nejdobře", "líple"], hint: "Adverb chain: dobře → líp/lépe → nejlíp/nejlépe." },
  { lessonId: "lesson2", type: "mc", q: "moc → ___ → nejvíc (more)", a: "víc", options: ["víc", "mnohem", "hodně", "mocnější"], hint: "moc → víc/více → nejvíc/nejvíce." },

  // ---- Lesson 3: locative, v/na/u, weather ----
  { lessonId: "lesson3", type: "mc", q: "Byl jsem ___ holiče. (at the barber's)", a: "u", options: ["u", "v", "na", "o"], hint: "u + Genitive = at someone's place." },
  { lessonId: "lesson3", type: "mc", q: "Čekám ___ nádraží. (at the train station)", a: "na", options: ["na", "v", "u", "o"], hint: "Stations & airports are exceptions: na nádraží, na letišti." },
  { lessonId: "lesson3", type: "mc", q: "Studuju ___ škole. (at school)", a: "ve", options: ["ve", "na", "u", "o"], hint: "ve škole (v/ve + Locative)." },
  { lessonId: "lesson3", type: "blank", q: "Dneska prší. Včera ___. (it rained)", a: "pršelo", hint: "Present → past: prší → pršelo." },
  { lessonId: "lesson3", type: "blank", q: "Dneska je zima. Včera ___ zima. (it was cold)", a: "byla", hint: "zima is feminine → byla zima." },
  { lessonId: "lesson3", type: "mc", q: "Mluvili jsme ___ kamarádovi. (about)", a: "o", options: ["o", "s", "z", "na"], hint: "o + Locative (6th case): o kamarádovi." },

  // ---- Lesson 4: past tense, znát/vědět/umět ----
  { lessonId: "lesson4", type: "mc", q: "___ plavat. (I know how to swim)", a: "Umím", options: ["Umím", "Vím", "Znám", "Můžu"], hint: "umět + infinitive = know how to." },
  { lessonId: "lesson4", type: "mc", q: "___ Prahu. (I know Prague)", a: "Znám", options: ["Znám", "Vím", "Umím", "Vidím"], hint: "znát + object = know a place/person/thing." },
  { lessonId: "lesson4", type: "mc", q: "___, kde je nádraží. (I know where...)", a: "Vím", options: ["Vím", "Znám", "Umím", "Chci"], hint: "vědět + clause = know a fact." },
  { lessonId: "lesson4", type: "mc", q: "jít → he went = ___", a: "šel", options: ["šel", "jitl", "chodil", "šla"], hint: "jít is irregular: šel (m) / šla (f) / šli (pl)." },
  { lessonId: "lesson4", type: "blank", q: "Včera ___ jsem byt. (uklidit — I, male, cleaned)", a: "uklidil", hint: "Past = stem + -l; male sg = -l." },
  { lessonId: "lesson4", type: "blank", q: "Narodila jsem ___ v roce 1990. (reflexive particle)", a: "se", hint: "narodit se; order is jsem + se." },

  // ---- Lesson 5: v/ve, time, dates, modals, jít na/do ----
  { lessonId: "lesson5", type: "mc", q: "___ dvanáct hodin. (at 12 o'clock)", a: "Ve", options: ["Ve", "V", "Na", "Do"], hint: "dvanáct starts with dv- cluster → 've', not 'v'." },
  { lessonId: "lesson5", type: "mc", q: "___ středu jdu do práce. (on Wednesday)", a: "Ve", options: ["Ve", "V", "Na", "O"], hint: "středa starts with st- cluster → 've'." },
  { lessonId: "lesson5", type: "mc", q: "___ pátek nemám čas. (on Friday)", a: "V", options: ["V", "Ve", "Na", "Do"], hint: "pátek has no tricky cluster → plain 'v'." },
  { lessonId: "lesson5", type: "mc", q: "Nechceš jít ___ kávu? (go for a coffee)", a: "na", options: ["na", "do", "v", "o"], hint: "jít na + accusative for activities/refreshments." },
  { lessonId: "lesson5", type: "mc", q: "Nechceš jít ___ restaurace? (go to the restaurant)", a: "do", options: ["do", "na", "v", "o"], hint: "jít do + genitive for enclosed places/buildings." },
  { lessonId: "lesson5", type: "mc", q: "Dneska nemůžu, ___ pracovat. (I must)", a: "musím", options: ["musím", "můžu", "chci", "mám"], hint: "muset (must): musím, musíš, musí + infinitive." },
  { lessonId: "lesson5", type: "blank", q: "1. ___ (May, genitive: '1st of May')", a: "května", hint: "Dates use genitive: květen → 1. května." },
  { lessonId: "lesson5", type: "blank", q: "September in Czech = ___", a: "září", hint: "The only neuter month; indeclinable." },

  // ---- Lesson 6: possessives, accusative, age, adjectives ----
  { lessonId: "lesson6", type: "mc", q: "To je ___ sestra. (my — before feminine noun)", a: "moje", options: ["moje", "můj", "jejich", "náš"], hint: "Feminine noun → moje/má; masculine → můj." },
  { lessonId: "lesson6", type: "mc", q: "To je ___ syn. (my — before masculine noun)", a: "můj", options: ["můj", "moje", "má", "její"], hint: "Masculine noun → můj." },
  { lessonId: "lesson6", type: "mc", q: "To je Adam a ___ syn → To je ___ syn. (Adam's son)", a: "Adamův", options: ["Adamův", "Adamova", "Adamovo", "Adamský"], hint: "Masculine owner + masc. thing: -ův." },
  { lessonId: "lesson6", type: "mc", q: "To je Jana a její kočka → To je ___ kočka. (Jana's cat)", a: "Janina", options: ["Janina", "Janin", "Janino", "Janová"], hint: "Feminine owner + fem. thing: -ina." },
  { lessonId: "lesson6", type: "mc", q: "Hledám ___ bratra. (older, M animate accusative)", a: "staršího", options: ["staršího", "starší", "starým", "starého"], hint: "M animate accusative adjective: -ího." },
  { lessonId: "lesson6", type: "mc", q: "Mám ___ dceru. (small, F accusative)", a: "malou", options: ["malou", "malá", "malé", "malý"], hint: "Feminine accusative adjective: -ou." },
  { lessonId: "lesson6", type: "blank", q: "Kolik ti je? – Je ___ 25. (I'm 25 — 'to me')", a: "mi", hint: "Age uses dative: je mi (to me)." },
  { lessonId: "lesson6", type: "blank", q: "Můj tatínek… Je ___ 50 let. (he is 50 — 'to him')", a: "mu", hint: "Dative: je mu (to him)." },
  { lessonId: "lesson6", type: "mc", q: "Naše dcera už je ___. (healthy, feminine)", a: "zdravá", options: ["zdravá", "zdravý", "zdravé", "zdraví"], hint: "Feminine adjective ending: -á." },

  // ---- Lesson 7: dát si, k+dative, portions, demonstratives ----
  { lessonId: "lesson7", type: "mc", q: "___ neperlivou vodu. (I'll have — ordering)", a: "Dám si", options: ["Dám si", "Dáš si", "Dáte si", "Mám si"], hint: "dát si = to order; 'I' form is Dám si." },
  { lessonId: "lesson7", type: "mc", q: "Co si dáte ___ pití? (for drinking)", a: "k", options: ["k", "na", "do", "o"], hint: "k + dative = for a purpose (k pití, k jídlu)." },
  { lessonId: "lesson7", type: "mc", q: "___ pivo, prosím. (two portions)", a: "Dvakrát", options: ["Dvakrát", "Dva", "Dvě", "Druhý"], hint: "Portions use multiplicative adverbs: dvakrát." },
  { lessonId: "lesson7", type: "mc", q: "___ kuře je dobré. (that — chicken is neuter!)", a: "To", options: ["To", "Ten", "Ta", "Ty"], hint: "kuře is NEUTER → To kuře." },
  { lessonId: "lesson7", type: "mc", q: "___ rýže je dobrá. (that — rice is feminine!)", a: "Ta", options: ["Ta", "Ten", "To", "Ty"], hint: "rýže is FEMININE → Ta rýže." },
  { lessonId: "lesson7", type: "blank", q: "'I'll pay / the bill please' = ___", a: "zaplatím", hint: "zaplatit → Zaplatím." },

  // ---- Lesson 8: future tense, go-verbs, kde/kam, direction ----
  { lessonId: "lesson8", type: "mc", q: "Zítra ___ pracovat celý den. (ongoing future — I will)", a: "budu", options: ["budu", "jsem", "byl", "budou"], hint: "Ongoing future = budu + infinitive." },
  { lessonId: "lesson8", type: "mc", q: "___ ti večer. (I'll call — single action)", a: "Zavolám", options: ["Zavolám", "Budu volat", "Budu zavolat", "Volám"], hint: "Perfective present = future; no 'budu'. Never 'budu zavolat'." },
  { lessonId: "lesson8", type: "mc", q: "___ do kina. (I'll go on foot)", a: "Půjdu", options: ["Půjdu", "Pojedu", "Poletím", "Jdu"], hint: "On foot: jít → půjdu." },
  { lessonId: "lesson8", type: "mc", q: "___ na letiště. (I'll go by vehicle)", a: "Pojedu", options: ["Pojedu", "Půjdu", "Poletím", "Jedu"], hint: "By vehicle: jet → pojedu." },
  { lessonId: "lesson8", type: "mc", q: "Půjdu ___ kina. (into the cinema — building)", a: "do", options: ["do", "na", "k", "v"], hint: "do + genitive for enclosed places." },
  { lessonId: "lesson8", type: "mc", q: "Půjdu na návštěvu ___ kamarádce. (to a person)", a: "ke", options: ["ke", "do", "na", "v"], hint: "To a PERSON = k/ke + dative (ke kamarádce)." },
  { lessonId: "lesson8", type: "mc", q: "O víkendu pojedeme ___ hory. (to the mountains)", a: "na", options: ["na", "do", "k", "v"], hint: "hory take 'na', not 'do'." },
  { lessonId: "lesson8", type: "blank", q: "'Take care!' (informal sign-off) = Měj se ___", a: "hezky", hint: "Měj se hezky!" }
];

/* Expose to the browser */
if (typeof window !== "undefined") {
  window.LESSONS = LESSONS;
  window.GRAMMAR_EXERCISES = GRAMMAR_EXERCISES;
}
