const SUPABASE_URL = "https://wjifojmrjxgbhhseqqld.supabase.co";
const SUPABASE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6IndqaWZvam1yanhnYmhoc2VxcWxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3ODcwMjg4NjUsImV4cCI6MjEwMjYwNDg2NX0.i4Y28pEWx5mSyO39U6m9G-BjF-RYcAntiGKS0mwNxSg";
